image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

environment:
  MSBUILD_LOGGER: C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll

build_script:
  - msbuild build\AppVeyor.proj /r /t:UpdateBuildVersion /logger:"%MSBUILD_LOGGER%"
  - msbuild Moq.sln /r /t:Build;Test;Pack /logger:"%MSBUILD_LOGGER%"

test: off

deploy:
  - provider: NuGet
    api_key:
      secure: 7MS5+XWaFchMXFqzgneQCqo9U0DlxiPXe/KWWUnbCBDEizVn06EjdQZkWu1gbNOJ
    artifact: Package
    on:
      appveyor_repo_tag: true

nuget:
  project_feed: true

artifacts:
  - path: out\*.nupkg
    name: Package
